### ISSUE TITLE
Supported versions of Java?

### ISSUE THREAD

**Issue by skyhirider** [HtmlUnit/htmlunit#10]
Which versions of Java does HtmlUnit support? 

I did not find any mention if it does support Java9+ and no luck building it myself so far, keep getting

`java.lang.module.FindException: Unable to derive module descriptor for \xalan-2.7.2.jar`

**Comment by ghost** [comment]
Have you found any solution?
htmlunit needs some serious upgrade to support java 9 and above

**Comment by skyhirider** [comment]
> Have you found any solution?
> htmlunit needs some serious upgrade to support java 9 and above

I am running HtmlUnit with OpenJdk11.0.1 in Eclipse 2018-12.

The trick is to not add it as a dependency into the modulepath, but to the classpath instead.

Everything works fine then.

**Comment by ghost** [comment]
welp! I was hoping for a more optimal solution, maybe I should wait for htmlunit to upgrade or switch back to OpenJDK8..

**Comment by skyhirider** [comment]
Are there any disadvantages of not using modulepath apart form the compiled code taking more space, both when running and on the disk?

For me it was an acceptable solution, I got it working with hopefully the other benefits of the newest Java left attached.

**Comment by ghost** [comment]
#### ! Warning this comment might seem like someone from an angry reddit community wrote it, so you can always choose to ignore this, or ask me to delete this.

> Are there any disadvantages of not using modulepath apart form the compiled code taking more space, both when running and on the disk?

Actually there is a problem, but not everyone faces it.
Adding dependencies to classpath doesn't make it not-a-module, in fact it is treated as an unnamed module which exports all packages and can access all packages (which module system doesn't allow). it usually doesn't create a problem though. ~~(this only happens if you are using a combination of classpath and modules)~~

But issues come when one module reads packages from different libs. Mostly it will be shown during maven/gradle build.
it looks like something this
"module A reads package B from both C and D "

It is something that I faced when trying build htmlunit with java11,
some of the libraries that htmlunit uses also have not migrated to java 9 or above.
example [apache-commons](http://apache-commons.680414.n4.nabble.com/Modular-version-edition-of-Apache-Commons-td4715174.html). 

Similar issues are being reported everywhere since java9, yes it broke a lot of libraries!

If it is just a warning, we could ignore that and patch it up later. but when I used htmlunit with javafx.web module on  openjfx11 everything started to break due to split packaging. 

### There are different solutions for this.
1. Add everything in classpath and use it like java 8. (I would rather go back to using java 8.)
1. Exclude conflicting packages using gradle/maven exclude functions  [like this](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360001517680-Error-java-module-A-reads-package-B-from-both-C-and-D-on-Java-11-project).
1. Merge the conflicting jars to single jar file.
1. Migrate every dependencies to java 9 and above and make them modular.

If you are creating an app or trying to run some tests none of these actually matter. just getting your code running will be your first priority.

But what if I want to create a library with dependency to some jar that is not modular?
people will start whining the same way that I am doing here right now to make it modular so that it would future compatible.

### So I have 4 solutions that would work for me.
1. Stick with OpenJDK 8.
1. Wait for all libraries to upgrade while I'm using OpenJDK 8.
1. Try doing that task on my on and contribute to htmlunit somehow with my **noob knowledge**..
1. Do nothing and drop my project like all of my other side projects.

I am trying option 3 right now with a lot of build errors, but I may be able to fix them or I will just fail at it..

**Comment by slonopotamus** [comment]
It isn't clear what exactly doesn't work but expected to from this issue.

**Comment by baha2046** [comment]
The Package netscape inside htmlunit package will conflict with jdk.jsobject.
And will getting XXX module reading netscrape.javascrape from both htmlunit and jdk.jsobject error.
The netscape folder inside htmlunit should remove and use the jdk.jsobject version.

**Comment by twendelmuth** [comment]
Well that would also require an update of the project to java 9.

I guess the easiest way to achieve functionality for java 8 and java9++ is to extract the netscape.javascript into it's own project, release it and reference it in the pom.

By that any Java9++ project with modules can exclude the reference to netscape.javascript and will no longer face issues of duplicated modules.

**Comment by skyhirider** [comment]
I've been using HtmlUnit for several years now with the latest Java version without any issues so I don't think its a problem anymore, therefore will close my own issue.
