### ISSUE TITLE
Uploaded PNG image always have application/octet-stream content type

### ISSUE THREAD

**Issue by php-coder** [HtmlUnit/htmlunit#18]
During upgrade to a newer version of htmlunit, my tests have started to fail because uploaded image (`test.png`) now has incorrect `application/octet-stream` content type. It looks like `image/png` type isn't supported by any browser:

https://github.com/HtmlUnit/htmlunit/blob/537b06332f6e4a24a8c9bbf657db348ce6a0d43a/src/main/java/com/gargoylesoftware/htmlunit/BrowserVersion.java#L233-L322

Could you confirm that it's indeed a bug?
Do you see what workaround could be applied in this case (except renaming a file to `test.jpg`)?

**Comment by rbri** [comment]
Yes you are right, i think this is a bug. Fix is on the way, you can use the next snapshot build if you like.

Because the list of upload mime types depends for real browsers on the operation system and the installed applications at the client side, you are already able to add more mime types (e.g. if you like to simulate a client where MS Office is installed).

Simply call
      `CHROME.registerUploadMimeType("png", "image/png");` 
or
      `FF60.registerUploadMimeType("png", "image/png");` 
or
    ....
before creating the WebClient with the browser.

Hope that helps.
Thanks for the report and for using HtmlUnit.

**Comment by php-coder** [comment]
Thanks for the fix!

BTW it's possible to close the issues with a special comment on the commits -- https://help.github.com/en/articles/closing-issues-using-keywords This way they will be connected and it becomes possible to jump from one to another in UI. JFYI.

**Comment by rbri** [comment]
Yep, good point - i simply forgot that.
