### ISSUE TITLE
Anchor.getTextContent not trimming the stlying tag

### ISSUE THREAD

**Issue by sowjanyaboddeti** [HtmlUnit/htmlunit#265]
`<a href="https://www.nextbiometrics.com/news_archive_2020/next-biometrics-receives-initial-purchase-order-of-5000-fap20-sensors-from-new-partner/">
--
   
  <style>
   h6.additional-class-50612681{
   line-height:  24px;
   font-size:  22px;
   letter-spacing:  -1px;
   }
   </style>        <h6 class=" additional-class-50612681  bd-content-element">
   
   NEXT Biometrics receives initial purchase order of 5000 FAP20  sensors from new partner.            
   </h6>
    
   </a>
`

While getting anchor text from the above href link, getting the styling tag included. Is this expected for some URLs (like outliers for the general logic)

**Comment by rbri** [comment]
It will be a great help if you can prepare a pull request with a failing test case similar to com.gargoylesoftware.htmlunit.html.HtmlAnchor2Test.asText_getTextContent()

**Comment by sowjanyaboddeti** [comment]
Created it https://github.com/HtmlUnit/htmlunit/pull/267

Submitted a PR in a public repo for the first -time. Please let me know if it doesn't look good.

**Comment by rbri** [comment]
Great, thanks.
Was simpler to understand your point based on the PR.
Have added a modified test com.gargoylesoftware.htmlunit.html.HtmlStyleTest.asText_getTextContent_insideDiv().

I think this is not a bug - the implementation works as expected (from my understanding) because getTextContent is a method inherited from org.w3c.dom.Node (see https://www.w3.org/TR/dom41/#dom-node-textcontent).

I guess for your case you have to use com.gargoylesoftware.htmlunit.html.DomNode.asText().

**Comment by sowjanyaboddeti** [comment]
asText() method works as expected. Thanks!
