### ISSUE TITLE
Scrape Page with Cloudflare Rocket Loader Running Javascript

### ISSUE THREAD

**Issue by ozu8** [HtmlUnit/htmlunit#353]
The page that I'm trying to scrape uses Cloudflare Rocket Loader to execute Javascript, and there is one script in particular that retrieves articles in consecutive 15-article chunks, observable in the browser. I'd like to mimic this using HTMLUnit, run the scripts and afterwards capture all 200 articles from the loaded page.

(Version 2.42.0)

```
public class Test {
    public static void main(String[] args) throws IOException {
        int count = 0;
        try (WebClient webClient = new WebClient(BrowserVersion.FIREFOX_68)) {
            webClient.getCache().clear();
            webClient.getOptions().setUseInsecureSSL(true);
            webClient.getOptions().setCssEnabled(false);
            webClient.getOptions().setJavaScriptEnabled(true);
            webClient.getOptions().setRedirectEnabled(true);
            webClient.getOptions().setDownloadImages(false);
            webClient.getCookieManager().setCookiesEnabled(true);
            webClient.getOptions().setThrowExceptionOnScriptError(true);
            webClient.getOptions().setThrowExceptionOnFailingStatusCode(false);
            webClient.setAjaxController(new NicelyResynchronizingAjaxController());
            webClient.setCssErrorHandler(new SilentCssErrorHandler());
            final HtmlPage page = webClient.getPage("https://www.mdpi.com/search?sort=pubdate&page_count=200&year_from=1996&year_to=2021&journal=applsci&view=compact");
            webClient.waitForBackgroundJavaScriptStartingBefore(10000);

            //get all 200 articles
            final List<HtmlDivision> divs = page.getByXPath("//div[contains(@class, 'generic-item article-item')]");
            for (HtmlDivision div : divs) {
                System.out.println(count++ + "\t" + div.getTextContent());
            }
            System.out.println("Found " + count + " of an expected 200 articles");
        }
    }
}
```
Running this yields only 15 of the desired 200 articles, and errors such as the following:

	May 12, 2021 1:14:42 PM com.gargoylesoftware.htmlunit.html.HtmlScript isExecutionNeeded
	WARNING: Script is not JavaScript (type: '4eca6d626edb4bb11e74dead-text/javascript', language: ''). Skipping execution.

So the Javascript is not run, due to not being recognized as Javascript, and in particular the type attribute ('4eca6d626edb4bb11e74dead-text/javascript') seems to be tripping up that recognition.

One twist is that the same code with Version 2.26 and BrowserVersion.FIREFOX_45 seems to ignore Rocket Loader, executes the Javascript as expected, and yields 200 articles.

Any help or insight would be greatly appreciated.

**Comment by rbri** [comment]
Good news - was able to fetch all 200 entries here - after spending two really long debugging sessions on the minimized Cloudflare Rocket Loader code (thanks again to https://www.charlesproxy.com/ - this tools is essential for this kind of tasks).

Background - the rocket loader works by
* replacing the type of your javascript blocks with this strange types you have seen in the log
* this types are ignored by the browsers and HtmlUnit does the same (plus inform in the log about this) - this is the reason why the pages are loading faster with the rocket loader
* the 'only' script that gets loaded is the cloudflare-static/rocket-loader.min.js script
* this script starts after the page is loaded and processes/loades this scripts step by step

There was a bug in HtmlUnit that prevents the rocket-loader.min.js to do the right thing - the document.contains() method returns false in all cases.

Have fixed the bug - now the test suite is running. Will inform as always via twitter if i have a new snapshot build ready.

You have to:
* wait for the new snapshot
* switch with you project to the latest snapshot build
* change this code  webClient.getOptions().setThrowExceptionOnScriptError(false); - you have to use false here because there seems to be another problem with one of the included js files.

This results here finally in loading all 200 items.

Please check and provide feedback about your progress.

**Comment by rbri** [comment]
there is a new snapshot available

**Comment by ozu8** [comment]
Many thanks, rbri! Really appreciate that you put time into this. One thing that I'm curious about is how specifically you used Charles Proxy in this instance. I experimented with breakpoints and Map Local, but mostly I was looking at the logs. Could you possibly share your process or any tips or tricks? Thanks again.

**Comment by rbri** [comment]
> specifically you used Charles Proxy in this instance

Good point - have to think about some video about this kind of debugging.

Generally i use map local and replacing the file content with the already formatted code from Charles. After that the line numbers of the error are useful. And i can start to add console.log statements. Then i compare the output from the browser and HtmlUnit to nail down the place where HtmlUnit starts to behave different.

In your case it was a bit more tricky because there was no exception only some log output from the loader. I had to guess a bit where to start with the logging.

**Comment by ozu8** [comment]
I can confirm that the code now runs as as expected. Thanks again, rbri! I'd be very interested in that video, should you make one!

**Comment by rbri** [comment]
Thanks enjoy using HtmlUnit.
