### ISSUE TITLE
WeakMap - TypeError: Expected argument of type object, but instead had type object 

### ISSUE THREAD

**Issue by SebastianPaulo** [HtmlUnit/htmlunit#373]
I use HTMLUnit to test a webpage with a 3rd party library (TinyMCE). 
The library is using a WeakMap to has additional stuff for documents it stores (Documents being the keys of the WeakMap). 
In all browsers this works fine. 
However HTMLUnit is throwing a TypeError ```Expected argument of type object, but instead had type object``` (Which by description alone is kind of odd). 

# Investigation
I traced the problem to: ```document```s are represented as DocumentProxy in HTMLUnit, which are not implementing Scriptable; and therefore not considered an object by Rhino (ScriptRuntime.isObject returns false). 
Based on browser engines ```typeof domNode``` is ```object```.

I think this is a bug, which needs a fix. However I am not sure if it's needed to be fix in htmlunit or in Rhino.

# Steps to repeat
I attached a minimal reproduction project to illustrate the issue.
[bug-demo.zip](https://github.com/HtmlUnit/htmlunit/files/6960452/bug-demo.zip)
(run ./gradlew test)

**Comment by rbri** [comment]
Hi Sebastian,
many thanks for the report and the great description / sample. I'm able to reproduce this here based on your code.
From my point of view this is a Rhino issue - because the Delegator is a Rhino feature. Sadly this is not at all places taken into account.

If you like to know a bit more about the details you can have a look at https://github.com/mozilla/rhino/pulls?q=is%3Apr+delegator

Will try to make another pr for Rhino and discuss there.

**Comment by rbri** [comment]
Made a Rhino PR lets see....

Give me an hint if you need the fix soon - i can do this in the HtmlUnit Rhino fork for the moment.

**Comment by rbri** [comment]
Made a new snapshot build - using the latests core-js snapshot including the fix for this.

**Comment by SebastianPaulo** [comment]
Hi RBRi, thanks for the quick support! On our side, some time off caused a delay in checking it out, but now I managed to review it. I will be happy to test the snapshot in one of our upcoming releases, and I will get back to you with feedback. So long, thanks for all the fish, greetings from Jena!
