### ISSUE TITLE
value attribute set with jquery selector can't be changed via HtmlInput Element

### ISSUE THREAD

**Issue by thuri** [HtmlUnit/htmlunit#422]
Hi, first of all thanks for all the work you've done on that project.

I may have found a bug or I am unaware of an mistake in my code.
To reproduce the issue I have setup a small test project: https://github.com/thuri/htmlunit-jquery-selector-init 
It uses:
* Java 11
* JUnit 5
* HTMLUnit 2.56.0

The html page of the project defines a small form with two fields, a text input and a datetime-local input. (But i actually don't think that the type has anything to do with the problem).

The page also contains a little javascript code that uses jquery to define an event handler for the ready event.
In that code I try to initialize the values of the inputs using the .val() function of jquery. This seems to work as i'm able to read the values with HTMLUnit.

```javascript
  $("#textField").val("Initialised");
  $("#timestampField").val("2021-12-17T15:15");
```
After that the code registers an submit handler for the form that is only used to log the values and skip the actual sending of the form, as there isn't an actual backend to receive the values.

Within the unit test I try to override the values like this:

```java
   form.getInputByName("textField").setValueAttribute("Foobar");
   form.getInputByName("timestampField").setValueAttribute("2021-12-31T12:00");
```
when the form is submitted the event handler is called as expected but the values set within the test are not available to the jquery handlers which can be seen in the console log. 

And the values are also unchanged in the HtmlPage returned by the click handler which will make the junit test in the project fail.

If the initializing is done without jquery the submit Handler get's the correct values and the result HtmlPage also contains the correct values:

```javascript
   document.forms.theform.textField = "Initialised";
   document.forms.theform.timestampField = "2021-12-17T15:15";
```

It would be great if you could have a look at this and probably tell me whether I've made a mistake or confirm that there is something strange happening here.

Thanks in advance,
Michael

**Comment by rbri** [comment]
Hi Michael,

at first many thanks for the detailed error description and the test project. Reports like this are the reason for having fun  working on libs like this.
I guess that your problem is related to infamous js async processing required to make all the web hacks around on this weak platform possible - what i like to say the jQuery ready function is async.

What seems to happen

**webClient.getPage()**
1.  retrieves the page, resolves the js stuff and runs the js that has to run
2. the jQuery stuff kicks in and assings the handlers
3. the jQuery ready gets started but the function is called async - means HtmlUnit does not wait for this to finish!

**webClient.setValueAttribute()**
1.  your update takes place

**maybe now**
1. the async handler starts his work and your values are overwritten

I think the idea is clear, the motivation of the jQuery folks to do it this way is also more or less clear; and for developers using jQuery this is more or less invisible.

Ok, but what to do - as always you have to be a bit more patient (or use a tool that does the magic for you www.wetator.org :-) ).

     webClient.waitForBackgroundJavaScript(100);

simply add this line after the getPage call to process the async ready handler.


Hope that helps (Und viele Grüße nach Thüringen)

**Comment by thuri** [comment]
Hey @rbri  thanks for the fast response.
You're right it looks like a race condition. Adding the line to the code really solved the problem (so I'll close the issue)
I just recently experienced the same issue with the the "native" javascript code within the ready function. 
But as you said the problem is the ready function as such not the way the inputs are accessed.

I don't know whether it is possible but i think it would be great if the webclient could be configured to wait for the javascript engine to complete. Because waiting for any amount of time in the test could result in flaky behavior. Sometimes the tests will be green and sometimes they will fail just because the machine had a bad day :-)

I understand that this wouldn't be a good idea if the javascript code creates reoccurring times as the JavaScript Engine won't complete. But anyway just some thoughts ...

**Comment by rbri** [comment]
Thanks @thuri for the fast feedback, great to see the problem is 'gone' - github stars are always welcome :-)

There are several wait methods to mitigate the wait problem. We have implemented a much more sophisticated wait handling in Wetator - if you are interested you can have a look at the source. And also WebDriver has some idea of waitFor in the API.

Maybe one day i have a final idea how to solve this the right way.....
