### ISSUE TITLE
will it support to get screenshot

### ISSUE THREAD

**Issue by seedily** [HtmlUnit/htmlunit#45]
While using Selenium tool, its drivers, such as PhantomJSDriver,ChromeDriver or some others, which extends RemoteWebDriver, can get the screenshot,  

As HtmlUnitDriver doesn't extend, there's no way to get screenshot. It may be wonderful for htmlunit to do it

**Comment by rbri** [comment]
The problem here is that HtmlUnit is a headless driver. This means there is no page layouting/rendering and as a result there is no chance to make a screenshot comparable to Selenium.

If you like you can have a look at WETATOR (wetator.org) and at the source code of the HtmlUnit backend (https://wetator.repositoryhosting.com/trac/wetator_wetator/browser/trunk/wetator/src/org/wetator/backend/htmlunit). There i have implemented a 'XHtml' screenshot - maybe this is an option for you.
