### ISSUE TITLE
Htmlpage.getPage returns empty webpage for a couple of urls

### ISSUE THREAD

**Issue by sowjanya143** [HtmlUnit/htmlunit#459]
Tried using 2.59.0 version but still result would an empty webpage for the below 2 URLs:

https://ir.youdao.com/
https://www.roku.com/investor/quarterly-results

**Comment by rbri** [comment]
Hi Sowjanya,

have done a quick look on both pages. In fact they contain no ordinary dom nodes at all - the whole page you see in your browser is created (on the fly) inside your browser by running javascript. And for both pages, the js code seems to fail in HtmlUnit because not all current language features are supported. The js support is constantly improving but still behind the browser.

What does this mean? This two pages are not supported at the moment and i don't have to time required to analyze the problem. If you are interested i really need a clear point to the misbehaving js funktion - if you like to analyze this i can give you some advice how to do that.

**Comment by sowjanya143** [comment]
Hi @rbri, Please let me know how to proceed with debugging, I would like to analyze and try to provide you a clear point of failure.

**Comment by rbri** [comment]
There is some description here https://htmlunit.sourceforge.io/submittingJSBugs.html

In general the idea is:
* make sure you are able to modify the js code used by the page that creates the problem (e.g. by using a web proxy that can manipulate the responses)
* use the proxy for the real browser and for HtmlUnit
* add log or alert statements to the code and try to get to the point where HtmlUnit differs from real browsers

**Comment by rbri** [comment]
did a quick test with version 3.0.0 and this pages are working now. Please open a new issue if you still have problems.
