### ISSUE TITLE
setJavaScriptEnabled(true) java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by 1362238576** [HtmlUnit/htmlunit#520]
running code：
		WebClient webClient = new WebClient();
		WebClientOptions options = webClient.getOptions();
		options.setJavaScriptEnabled(true);
		HtmlPage page = webClient.getPage("https://djsakldjsalkmdlwje.top");
		System.out.println(page.asXml());
		webClient.close();

Memory keeps growing ，why?
if  setJavaScriptEnabled(false)  Then normal，  However, some web pages are not complete ！

**Comment by rbri** [comment]
There are many possible reasons for that and because the js code of the page seems to be obfuscated it will be hard to guess what is going wrong here.

In most cases this is related to some loops changing the content of a dom element until a specific size is reached - this kind of loops might run endless because HtmlUnit is headless.

From a first look i saw a script appinstall.js seems to run endless here.

Because the real page starts a download automatically i guess this page tries to do something bad - will no  longer invest time.
Sorry.
