### ISSUE TITLE
[Regression 2.6x?] DateTimeFormat.format() missing and other weirdness

### ISSUE THREAD

**Issue by duonglaiquang** [HtmlUnit/htmlunit#529]
# Problem in brief

Attempts to call the JS method `DateTimeFormat.format()` in HtmlUnit 2.66 now throws `TypeError: Cannot find function format in object [object DateTimeFormat]` where as in a much older 2.52 it ran as expected.

[This commit](https://github.com/HtmlUnit/htmlunit/commit/2642336fb31492af473163e1a61f58de1d27286b) released in HtmlUnit 2.64 may have unintentionally removed it by removing the `RecursiveFunctionObject.call()` override.

# Reproducing

Here's an example HTML to reproduce:

```html
<!DOCTYPE html>
<html>
<head>
<script>

let dateFormat = Intl.DateTimeFormat();
console.log(dateFormat.format(new Date(2022, 11, 19))) // throws TypeError
console.log(dateFormat instanceof Intl.DateTimeFormat) // returns false instead of true

</script>
</head>
<body>
</body>
</html>
 
```

# More details

Locally restoring `RecursiveFunctionObject.call()` had the effect of making the test above run as expected.

**Comment by rbri** [comment]
Strange, can reproduce this - will have a look later today.

**Comment by rbri** [comment]
ok found it fix will be available soon

**Comment by rbri** [comment]
fixed, waiting for the CI

**Comment by duonglaiquang** [comment]
That was fast. Thanks for the response, I have tested your fix and have confirmed it works.

Should I close the issue? Not sure.. I'll close it this time

**Comment by rbri** [comment]
Because you have confirmed i think closing is ok. Usually i close the issues if the code is in the wild (snapshot is available).
The jenkins had some problems yesterday - hope it will be back with with the right performance today. Then i will build a new snapshot and inform on twitter like always.

The fix was fast because you did all the painful work of finding the issue, making up the test case and also pointing to the commit. The rest was the easy part... Thanks again.

Hope you will not face more of this regressions.

And BTW: all the best for you your family and all around (@atnak included :-)) for 2023
