### ISSUE TITLE
I got an exception in SgmlPage class. 

### ISSUE THREAD

**Issue by Kartofanych** [HtmlUnit/htmlunit#542]
Supertypes of the following classes cannot be resolved. Please make sure you have the required dependencies in the classpath:
    class com.gargoylesoftware.htmlunit.SgmlPage, unresolved supertypes: org.w3c.dom.traversal.DocumentTraversal
 How could i solve this problem? Actually I dont need this class, but I get error from it

**Comment by rbri** [comment]
you are on android?

**Comment by Kartofanych** [comment]
> you are on android?

yep

**Comment by rbri** [comment]
This is a know problem with HtmlUnit on android (i guess you are already using the android package - https://github.com/HtmlUnit/htmlunit-android.

In general some classes from the java platform are not available on android - this produces this kind of problems.
But i can't solve this for you case not without breaking the backward compatibility for others.

Because of this i plan to start working on something that will become HtmlUnit 3 later this year. So you have to be a bit patient here - i'm not really sure about a release date of a first snapshot version.

Do you have any deadlines?

**Comment by Kartofanych** [comment]
Oh, nice. 
No, I am just trying to learn something new) I will follow your research)

**Comment by rbri** [comment]
ok, you can follow htmlunit on twitter also (https://twitter.com/htmlunit)

**Comment by rbri** [comment]
@Kartofanych 
Can you please try with htmlunit-android 3.0.0-SNAPSHOT and report your results here.

**Comment by rbri** [comment]
no feedback i guess this is fixed now
