### ISSUE TITLE
Click is not working for pn:menuItem

### ISSUE THREAD

**Issue by Mohana-Priya** [HtmlUnit/htmlunit#632]
Hi, 
We have upgraded Jquery from 1.5.1 to 3.7.0 and our project is based on Rich faces version 4.0.0
After Jquery upgrade I upgraded htmlunit from 2.17 to 3.4.0. Now after upgrade below test 

        @Test
    public void testServerClick() throws IOException, SAXException {
        HtmlPage page = environment.getPage("/dropDownMenu_serverMode.jsf");
        HtmlDivision item = (HtmlDivision) page.getElementById("form:saveAll");
        assertNotNull(item);
        DropDownMenuBean.setCurrent("none");
        item.click(); 
        item = (HtmlDivision) page.getElementById("form:saveAll");
        assertNotNull(item);
        assertEquals("action", DropDownMenuBean.getCurrent());
    }

is failing with warning 
WARNING: Calling click() ignored because the target element 
HtmlDivision[<div class="rf-ddm-itm rf-ddm-itm-unsel " id="form:saveAll">] is not displayed.

I verified item.isDisplayed() , it is returning false only. 
I have tried  page.wait or set innerheight etc., but nothing helps.

Could you please let me know how to fix this test?

**Comment by rbri** [comment]
Hi @Mohana-Priya,
great to see that HtmlUnit helps you to do your stuff - and from 2.17 to 3.4.0 is a huge step (forward :-))

Without some more information it is hard to tell what is going on. Maybe you can do the following
* go to the page in question in the real app using a real browser (chrome or ff)
* open the developer tool and have a look at the div tag in question, check for the styles
* make a screenshot of the devtools showing the div tab
* now back to your tests
* change the code and add  System.out.println(page.asXml()); right before clicking the div tag
* check the output - have a look at the div tag in this output - maybe you can already see the difference that might be the reasons
* otherwise send me the output and i will have a look

The page.asXml() helps to get an view how HtmlUnit sees the page - maybe some jQuery actions are not processed or maybe some styles are not applied - let's see.

**Comment by Mohana-Priya** [comment]
Hi Thanks a lot for reply!

Replacing item.click() with item.click(false, false, false, true, true,true, false); as per https://htmlunit.sourceforge.io/faq.html#clickNotWorking fixed the issue.

**Comment by rbri** [comment]
yes, but if the div is visible/clickable in real browsers it should also be in HtmlUnit

**Comment by rbri** [comment]
Ok, the solution works, will close this.
Please open a new one if you facing other problems.

Thanks for the report!
