### ISSUE TITLE
DefaultJavaScriptExecutor running even if WebClient has javascript disabled

### ISSUE THREAD

**Issue by cdalexndr** [HtmlUnit/htmlunit#65]
On WebClient I set the following option, but the executor still starts:
`webClient.getOptions().setJavaScriptEnabled( false )`
The `DefaultJavaScriptExecutor `runs a loop with `Thread.sleep(10ms)` that has impact on performance.
The executor should use other mechanisms instead of the costly loop with Thread.sleep to wake when there are jobs pending.

Note that this executor has **top** usage in my java profiler's hot spots.

htmlunit-2.36.0-SNAPSHOT

**Comment by rbri** [comment]
Valid point, something that seems to be there since ages.

Regarding the Thread.sleep loop - you are right, but this was implemented so long ago and it is really hard to change the impl at this point. I fear there will be no time in the near future to make some major changes here.
But contributions are welcome.

As always will inform via twitter if a new Snapshot build is available.
