### ISSUE TITLE
How to use Clipboard with WebClient?

### ISSUE THREAD

**Issue by chrc** [HtmlUnit/htmlunit#771]
Re-open #762 

Thanks you @rbri
But I get an HeadlessException error.

![Capture d’écran 2024-04-08 à 09 14 29](https://github.com/HtmlUnit/htmlunit/assets/88607/6b0c583b-5e13-47b3-8144-c8f3bd5afbf3)

**Comment by rbri** [comment]
That's expected, using the AwtClipbaordHandler will end like that if you java runtime is in headless mode - because the clipboard is something that requires a ui.

The trick is to implement you own ClipboardHandler (should be simple) and you are able to set/get the clipboard content and still run in headless mode.

**Comment by rbri** [comment]
ok, will try to add some more details about that to the https://www.htmlunit.org/details.html document....

**Comment by rbri** [comment]
Document updated - hope this is ok for you.

**Comment by rbri** [comment]
Will close this, please comment or open a new one if you think there is more required.

Thanks.
