### ISSUE TITLE
HtmlPage.executeJavaScript() encoding issue

### ISSUE THREAD

**Issue by xisvaldo** [HtmlUnit/htmlunit#9]
When trying to execute a Javascript function into a local HTML file [test.txt](https://github.com/HtmlUnit/htmlunit/files/2676966/test.txt) it is not returning correctly.

Code example: 

```
webClient = new WebClient(BrowserVersion.CHROME);
webClient.getOptions().setThrowExceptionOnScriptError(false);
webClient.getOptions().setCssEnabled(false);
webClient.getOptions().setAppletEnabled(false);
webClient.getOptions().setDownloadImages(false);

htmlPage = this.webClient.getPage("file:/" + htmlFile.getAbsolutePath());

ScriptResult scriptResult = htmlPage.executeJavaScript(expression);
```

The expression could be something like:
`title = document.querySelector('#productTitle').textContent.trim()`
or 
`category = 
document.querySelector('#wayfinding-breadcrumbs_feature_div > ul > li > span > a').textContent.trim()`.

According this sample file, the results are:
`"title": "Producto Uno Con AcentuaciÃ³n Para Probar Encoding. InterÃ©s y Otras Palabras Como AÃ±adir o BaterÃ­a"`
and
`"category": "ElectrÃ³nica"`

**Comment by rbri** [comment]
The problem here is the file source. There is information about the used encoding when reading a plain file from the disk. HtmlUnit handles this case the same way as if the web server does not provide any encoding information as part of the response. In these cases HtmlUnit (like real browsers) reads the file bytes using the StandardCharsets.ISO_8859_1 encoding.

As simple solution write your file ISO_8859_1 encoded.

Please report if this is a possible for you your case, if not we have to build a more complex solution.

**Comment by xisvaldo** [comment]
Perfect @rbri! Thanks for your support!
